### ISSUE TITLE
Lecture 9 

### ISSUE THREAD

**Issue by seopp** [sunmin-lee99/Tobigs_NLPseminar_2023#3]
Multi-head Attention을 할 때, 각 헤드들의 output을 concat 한 후 W^o matrix를 곱해줍니다.
각 layer의 input output 차원을 동일하게 유지하기 위해 W^o matrix를 곱해준다고 이해를 했습니다.
본 논문의 구현상으로는 512차원을 8개의 헤드로 나눠 각각의 헤드가 64차원을 가지고, concat 하면 d_model의 차원과 같아지는데 W^o matrix를 곱해주는 이유는 무엇인가요?
질문을 정리하자면, W^o matrix의 역할은 무엇인가요?
<img width="547" alt="image" src="https://user-images.githubusercontent.com/100005890/229798759-56e4d741-bfbb-4603-baf7-d412317ffd41.png">

**Comment by ckj18** [comment]
49 슬라이드에 있는 어텐션에 대한 그림으로 4종류가 있는데, 이것들이 의미하는 바가 무엇인지 궁금합니다.

**Comment by sunmin-lee99** [comment]
오늘 강의 전까지 찾아서 최대한 내용 추가해보겠습니다!

**Comment by sunmin-lee99** [comment]
강의 슬라이드에 올려주신 질문들에 대한 답변을 찾아서 최대한 내용 추가해보겠습니다!

**Comment by sunmin-lee99** [comment]
@ckj18 경주님 Lecture 9 슬라이드가 48 page 밖에 없는데 어떤 그림 말씀하시는건지 다시 한번 알려주실 수 있으신가요?

**Comment by ckj18** [comment]
2021 Winter에서 Recent work on improving on quadratic self-attention cost에 대한
슬라이드에 있는 그림입니다. 혹시 2021 Winter가 아니었나요?

2023년 4월 5일 (수) 오전 9:34, Sunmin Lee ***@***.***>님이 작성:

**Comment by sunmin-lee99** [comment]
@ckj18  2021 winter 맞습니다! 강의 자료에 있는 슬라이드 번호랑 강의 영상에 나오는 슬라이드 번호가 달라서 강의 영상 다시 확인했고 찾았습니다!
